### ISSUE TITLE
Is it possible to add authorization for form-data?

### ISSUE THREAD

**Issue by TechHoops** [premisedata/dynamic-data-form-extension#15]
Thanks for this plugin, it is very valuable for adding custom fields backed by data retrieved via APIs .

I just had one question what needs to be done to ensure authorization headers are passed when fetch is called by the front-end plugin for the form-data as the call goes to backstage backend and in our case we want to have auth enabled.

**Comment by nthings** [comment]
You may need to check the docs on how to do it on your backstage instance as this is handled on a level above of this plugin in the actual implementation: https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md
